config/routes.rb
Rails.application.routes.draw do
    scope PluginRoutes.system_info["relative_url_root"] do
      scope '(:locale)', locale: /#{PluginRoutes.all_locales}/, :defaults => {  } do
        # frontend
        namespace :plugins do
          namespace 'flexx_plugin_next_admin' do
            get 'index' => 'front#index'
          end
        end
      end

      #Admin Panel
      scope :admin, as: 'admin', path: PluginRoutes.system_info['admin_path_name'] do
        namespace :next do
          resources :campaigns
          resources :dashboard
          resources :settings

          namespace :website do
            root to: :index
            get :new_page
          end

          get "/crm" => "dashboard#crm"
          get "/media" => "dashboard#media"
          get "/messaging" => "dashboard#messaging"
          get "/conversations-email" => "dashboard#conversations_email"
          get "/gyms" => "dashboard#gyms"
        end

        namespace 'plugins' do
          namespace 'flexx_plugin_next_admin' do
            controller :admin do
              get :index
              get :settings
              post :save_settings
            end
          end
        end
      end

      # main routes
      #scope 'flexx_plugin_next_admin', module: 'plugins/flexx_plugin_next_admin/', as: 'flexx_plugin_next_admin' do
      #  Here my routes for main routes
      #end
    end
  end

app/models/plugins/flexx_plugin_next_admin/flexx_plugin_next_admin.rb
# class Plugins::FlexxPluginNextAdmin::FlexxPluginNextAdmin < ActiveRecord::Base
  # belongs_to :site, class_name: "CamleonCms::Site"

  # here create your models normally
  # notice: your tables in database will be plugins_flexx_plugin_next_admin in plural (check rails documentation)
# end

app/controllers/next/campaigns_controller.rb
class Next::CampaignsController < CamaleonCms::CamaleonController
  layout "flexx_next_admin"

  def index
  end

  def new
  end

  def show
  end

end

app/controllers/next/contacts_controller.rb
class Next::ContactsController < CamaleonCms::CamaleonController
  layout "flexx_next_admin"

  def index
  end

  def show
  end

end

app/controllers/next/dashboard_controller.rb
class Next::DashboardController < CamaleonCms::CamaleonController
  layout "flexx_next_admin"

  def index
    @active_contacts = current_site.contacts.active
  end

  def settings
  end

  def crm
  end

  def media
  end

  def messaging
  end

  def conversations_email
  end

  def conversations_text
  end

  def gyms
  end

  def website
  end

  def stock
  end

  def stock_new
  end
end

app/controllers/next/recipes_controller.rb
class Next::RecipesController < CamaleonCms::CamaleonController
  layout "flexx_next_admin"

  def index
  end

  def new
  end

  def show
  end

end

app/controllers/next/settings_controller.rb
class Next::SettingsController < CamaleonCms::CamaleonController
  layout "flexx_next_admin"

  def index
  end

end

app/controllers/next/website_controller.rb
class Next::WebsiteController < CamaleonCms::CamaleonController
  layout 'flexx_next_admin'

  def index
  end

  def new_page
    render :new_page, layout: 'contentbox'
  end
end

app/controllers/plugins/flexx_plugin_next_admin/admin_controller.rb
class Plugins::FlexxPluginNextAdmin::AdminController < CamaleonCms::Apps::PluginsAdminController
  include Plugins::FlexxPluginNextAdmin::MainHelper
  def index
  end

  # show settings form
  def settings
  end

  # save values from settings form
  def save_settings
    @plugin.set_options(params[:options]) if params[:options].present? # save option values
    @plugin.set_metas(params[:metas]) if params[:metas].present? # save meta values
    @plugin.set_field_values(params[:field_options]) if params[:field_options].present? # save custom field values
    redirect_to url_for(action: :settings), notice: 'Settings Saved Successfully'
  end
  # add custom methods below ....
end

app/controllers/plugins/flexx_plugin_next_admin/front_controller.rb
class Plugins::FlexxPluginNextAdmin::FrontController < CamaleonCms::Apps::PluginsFrontController
  include Plugins::FlexxPluginNextAdmin::MainHelper
  def index
    # actions for frontend module
  end

  # add custom methods below
end

app/helpers/plugins/flexx_plugin_next_admin/main_helper.rb
module Plugins::FlexxPluginNextAdmin::MainHelper
  def self.included(klass)
    # klass.helper_method [:my_helper_method] rescue "" # here your methods accessible from views
  end

  # here all actions on going to active
  # you can run sql commands like this:
  # results = ActiveRecord::Base.connection.execute(query);
  # plugin: plugin model
  def flexx_plugin_next_admin_on_active(plugin)
  end

  # here all actions on going to inactive
  # plugin: plugin model
  def flexx_plugin_next_admin_on_inactive(plugin)
  end

  # here all actions to upgrade for a new version
  # plugin: plugin model
  def flexx_plugin_next_admin_on_upgrade(plugin)
  end

  # hook listener to add settings link below the title of current plugin (if it is installed)
  # args: {plugin (Hash), links (Array)}
  # permit to add unlimmited of links...
  def flexx_plugin_next_admin_on_plugin_options(args)
    args[:links] << link_to('Settings', admin_plugins_flexx_plugin_next_admin_settings_path)
  end

  def get_plugin
    plugin = current_site.plugins.find_by_slug("flexx_plugin_next_admin")
  end

  def flexx_plugin_next_admin_on_render_admin_dashboard(args) # methods dont need to have these big names
    dashboard_route = get_plugin.get_option('dashboard_route')

    if dashboard_route == 'new'
      args.tap do |a|
        a[:layout] = "layouts/flexx_next_admin"
        a[:render] = "/next/dashboard"
      end
    end

  end
end

app/views/next/campaigns/index.html.erb
<header class="header">
  <div class="header-info">
    <h2 class="header-title">Your <strong>Campaigns</strong></h2>
  </div>
  <div class="header-action">
    <div class="buttons">
      <button class="btn btn-primary btn-float" data-toggle="modal" data-target="#modal_new_campaign"><i class="ti-plus"></i></button>
    </div>
  </div>
</header>

<div class="main-content">

  <p class="lead text-center text-fade">Active campaigns</p>
  <div class="card b-1 hover-shadow-2 mb-20">
    <a class="media card-body" href="/admin/next/campaigns/new">

      <div class="media-body">
        <div class="mb-2">
          <span class="fs-20 pr-16">Campaign Title</span>
        </div>
        <small class="fs-16 fw-300 ls-1">Brief campaign description</small>
      </div>

      <div class="media-right text-right d-none d-md-block">
        <p class="fs-14 text-fade mb-12">
          <span class="text-fade fs-12">Active participants: <strong>15</strong></span>
        </p>
      </div>
    </a>
    <footer class="card-footer flexbox align-items-center">
      <div>
        <strong>Created on:</strong>
        <span>Jan 21, 2017</span>
      </div>
      <div class="card-hover-show">
        <a class="btn btn-xs fs-10 btn-bold btn-info" href="#qv-stats-overview" data-toggle="quickview">Stats</a>
        <a class="btn btn-xs fs-10 btn-bold btn-danger recipe-delete" href="#">Delete</a>
      </div>
    </footer>
  </div>

  <br>
  <div class="divider text-uppercase fw-500">Drafts</div>

</div>

<div id="qv-stats-overview" class="quickview quickview-xxl backdrop-light">
  <header class="quickview-header">
    <p class="quickview-title lead"><strong>Campaign Title</strong></p>
    <span class="close"><i class="ti-close"></i></span>
  </header>

  <div class="quickview-body">
    <div class="quickview-block">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title"><strong>Emails</strong></h5>
        </div>

        <div class="card-body">
          <div class="flexbox flex-justified text-center">
            <ul class="list-unstyled">
              <li><small class="text-uppercase letter-spacing-1">Sent</small></li>
              <li><span class="badge badge-lg badge-ring badge-primary"></span></li>
              <li class="lead">250</li>
            </ul>

            <ul class="list-unstyled">
              <li><small class="text-uppercase letter-spacing-1">Opened</small></li>
              <li><span class="badge badge-lg badge-ring badge-info"></span></li>
              <li class="lead">120</li>
            </ul>

            <ul class="list-unstyled">
              <li><small class="text-uppercase letter-spacing-1">Bounced</small></li>
              <li><span class="badge badge-lg badge-ring badge-danger"></span></li>
              <li class="lead">50</li>
            </ul>
          </div>

          <br><br>

          <div class="text-center">
            <!-- <span data-provide="peity" data-type="donut" data-fill="#33cabb,#48b0f7,#f96868" data-size="150" data-inner-radius="68">250,120,50</span> -->
          </div>

        </div>
      </div>
    </div>
  </div>

  <footer class="quickview-footer">
    <button class="btn btn-secondary" data-dismiss="quickview">Close</button>
  </footer>
</div>

<!-- MODAL: New campaign modal -->
<div class="modal modal-top fade" id="modal_new_campaign" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New campaign</h5>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form class="card form-type-combine">

          <div class="card-body">

            <div class="form-groups-attached">

              <div class="form-group">
                <label>Campaign Name</label>
                <input class="form-control" type="text">
              </div>

              <div class="form-group">
                <label for="textarea">Campaign description</label>
                <textarea class="form-control" id="textarea" rows="6"></textarea>
              </div>

            </div>
          </div>
        </form>
        <div class="text-center">
          <p>(You can update this later)</p>
        </div>  
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-bold btn-pure btn-secondary" data-dismiss="modal">Cancel</button>
        <a href="/admin/next/campaigns/new" class="btn btn-bold btn-pure btn-primary">Continue</button>
      </div>
    </div>
  </div>
</div>

app/views/next/campaigns/new.html.erb
<style>
  input[type=radio].hide-control { display: none; }
</style>
<script>
  $('document').ready(function(){
    var stepFormPlaceholder = $("#step_placeholder");
    var stepForm = $("#new_step_form");
    var addStepBtn = $("#btn_add_step");
    stepForm.hide();
    addStepBtn.addClass('btn-primary');
    $(addStepBtn).on('click', function(e) {
      stepFormPlaceholder.toggle();
      stepForm.toggle();
      addStepBtn.toggleClass('btn-primary btn-warning disabled');
      $("#btn_add_step > i").toggleClass('ti-plus ti-more');
    });
  });
</script>
<header class="header">
  <div class="header-bar header-inverse bg-info">
    <a href="/admin/next/campaigns" style="color: #fff;"><i class="ti-arrow-left"></i> Back to campaigns list</a>
    <p class="fs-16">Creating new campaign</p>
  </div>

  <div class="header-info">
    <div class="left">
      <h2 class="header-title"><strong>Some title</strong> campaign <small class="subtitle">Description of Campaign (when clicking the edit button, need to add the "delete" button)</small></h2>
    </div>
  </div>

  <div class="header-action">
    <div class="buttons">
      <a class="btn btn-warning btn-float btn-sm" href="#" title="Edit title or description" data-provide="tooltip" data-placement="top"><i class="ti-pencil"></i></a>
      <a class="btn btn-success btn-float" href="#" title="Edit title or description" data-provide="tooltip" data-placement="top"><i class="ti-control-play"></i></a>
    </div>
  </div>
</header>

<div class="main-content">
  <div class="row">

    <div class="col-md-6">
      <div class="card">
        <h4 class="card-title"><strong>Campaign</strong></h4>
        <ol class="timeline timeline-activity timeline-point-sm timeline-content-right w-100 py-20 pr-20">
          <a href="#qv-edit-step" data-toggle="quickview">
            <li class="timeline-block">
              <div class="timeline-point">
                <span class="badge badge-ring badge-primary"></span>
              </div>
              <div class="timeline-content">
                <time datetime="2018">Immediately</time>
                <p>Add lead to mailing list</p>
              </div>
            </li>
          </a>    

          <a href="#qv-edit-step" data-toggle="quickview">
            <li class="timeline-block">
              <div class="timeline-point">
                <span class="badge badge-ring badge-info"></span>
              </div>
              <div class="timeline-content">
                <time datetime="2018">after 1 day</time>
                <p>Call and schedule initial consult</p>
              </div>
            </li>
          </a>

        </ol>
        <div class="card-footer text-center">
          <div class="fab">
            <button id="btn_add_step" class="btn btn-float" title="Add new step" data-provide="tooltip" data-placement="top"><i class="ti-plus"></i></button>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div id="step_placeholder" class="card card-transparent">
        <div class="card-body text-center">
          <h3 class="text-muted">Add a new step</h3>
        </div>
      </div>
      <form id="new_step_form" name="recipeStep" class="card form-type-combine">
        <h4 class="card-title"><strong>New step</strong></h4>

        <div class="card-body">
          <div class="form-group">
            <label for="select">Type</label>
            <select class="form-control" id="step_type">
              <option>Phone call</option>
              <option>Email</option>
              <option>Text</option>
              <option>General</option>
            </select>
          </div>

          <h6 class="text-light fw-300">Timing</h6>
          <div class="no-border text-center">
            <div class="btn-group" data-toggle="buttons">
              <label class="btn btn-lg btn-info active">
                <input class="hide-control" type="radio" name="timingOptions" id="option1" value="1" autocomplete="off" checked>Immediate</i>
              </label>
              <label class="btn btn-lg btn-info">
                <input class="hide-control" type="radio" name="timingOptions" id="option2" value="2" autocomplete="off">Schedule</i>
              </label>
            </div>
          </div>  

          <div id="timing_detail" class="form-groups-attached">

            <div class="row">
              <div class="form-group col-6">
                <label>After</label>
                <input class="form-control" type="text" placeholder="1">
              </div>

              <div class="form-group col-6">
                <label for="select">Time unit</label>
                <select class="form-control" id="select">
                  <option>minutes</option>
                  <option>hours</option>
                  <option>days</option>
                </select>
              </div>
            </div>

          </div>

          <br>
          <h6 class="text-light fw-300">Details</h6>
          <div class="form-groups-attached">

            <div class="form-group">
              <label>Title for reference</label>
              <input class="form-control" type="text">
            </div>

            <div class="form-group">
              <label>Description</label>
              <textarea class="form-control" rows="6"></textarea>
            </div>

          </div>


        </div>

        <footer class="card-footer text-right">
          <button class="btn btn-secondary" type="reset">Cancel</button>
          <button class="btn btn-primary" type="submit">Add</button>
        </footer>
      </form>
    </div>
  
  </div>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <h4 class="card-title"><strong>Associated forms</strong> (optional)</h4>

        <div class="card-body form-type-combine">
          <div class="row">


            <div class="col-md-6">
              <p>Use the list on the right to select forms associated with the recipe. Anyone submitting through the form will automatically have the task list applied to their account.</p>
            </div>


            <div class="col-md-6">
              <hr class="d-md-none">

              <div class="form-group">
                <h5>Forms</h5>

                <p>Add <code>multiple</code> froms</p>
                <!-- <select data-provide="selectpicker" multiple>
                  <option>Default contact</option>
                  <option>Consultation</option>
                  <option>Special event</option>
                </select> -->
              </div>
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</div> 


<!-- QUICKVIEW - Edit step -->
<div id="qv-edit-step" class="quickview quickview-xxl backdrop-dark">
  <header class="quickview-header">
    <p class="quickview-title lead">Edit: <strong>Step title</strong></p>
    <span class="close"><i class="ti-close"></i></span>
  </header>

  <div class="quickview-body">
    <form class="quickview-block form-type-combine">

      <div class="card-body">
        <div class="form-group">
          <label for="select">Type</label>
          <select class="form-control" id="step_type">
            <option>Phone call</option>
            <option>Email</option>
            <option>Text</option>
            <option>General</option>
          </select>
        </div>

        <h6 class="text-light fw-300">Timing</h6>
        <div class="no-border text-center">
          <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-lg btn-info active" style="width: 100%;">
              <input class="hide-control" type="radio" name="timingOptions" id="option1" value="1" autocomplete="off" checked>Immediate</i>
            </label>
            <label class="btn btn-lg btn-info" style="width: 100%;">
              <input class="hide-control" type="radio" name="timingOptions" id="option2" value="2" autocomplete="off">Schedule</i>
            </label>
          </div>
        </div>  

        <div id="timing_detail" class="form-groups-attached">

          <div class="row">
            <div class="form-group col-6">
              <label>After</label>
              <input class="form-control" type="text" placeholder="1">
            </div>

            <div class="form-group col-6">
              <label for="select">Time unit</label>
              <select class="form-control" id="step_time_unit">
                <option>minutes</option>
                <option>hours</option>
                <option>days</option>
              </select>
            </div>
          </div>

        </div>

        <br>
        <h6 class="text-light fw-300">Details</h6>
        <div class="form-groups-attached">

          <div class="form-group">
            <label>Title for reference</label>
            <input class="form-control" type="text">
          </div>

          <div class="form-group">
            <label>Description</label>
            <textarea class="form-control" rows="6"></textarea>
          </div>

        </div>


      </div>

      <footer class="card-footer text-right">
        <button class="btn btn-secondary" type="reset">Cancel</button>
        <button class="btn btn-primary" type="submit">Save</button>
      </footer>
    </form>
  </div>

  <footer class="quickview-footer flex-row-reverse">
    <button class="btn btn-danger" type="submit">Delete step</button>
  </footer>
</div>

app/views/next/dashboard.html.erb
<script type="text/javascript">
  window.location.href="/admin/next/dashboard"
</script>

app/views/next/dashboard/index.html.erb
<div class="main-content">

  <div class="row">

    <div class="col-lg-3 col-md-6">
      <div class="card">
        <div class="card-body">
          <div class="flexbox">
            <h5>Tasks</h5>
            <span class="float-right"><a class="btn btn-xs btn-primary" href="/admin/next/tasks">View</a></span>
          </div>

          <div class="text-center my-2">
            <div class="fs-60 fw-400 text-info">34</div>
            <span class="fw-400 text-muted">Due Today</span>
          </div>
        </div>

        <div class="card-body bg-lighter fw-400 py-12">
          <span class="text-muted mr-1">Completed:</span>
          <span class="text-dark">16</span>
        </div>

        <div class="progress mb-0">
          <div class="progress-bar bg-info" role="progressbar" style="width: 45%; height: 3px;" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="card card-transparent b-1 h-200px">
        <header class="card-header">
          <h4 class="card-title">EMPTY</h4>
          <a class="btn btn-sm btn-flat btn-info" href="#">Add Widget</a>
        </header>

        <div class="card-body">
          <p>Click the "Add Widget" button to select from the widget options.</p>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="card card-transparent b-1 h-200px">
        <header class="card-header">
          <h4 class="card-title">EMPTY</h4>
          <a class="btn btn-sm btn-flat btn-info" href="#">Add Widget</a>
        </header>

        <div class="card-body">
          <p>Click the "Add Widget" button to select from the widget options.</p>
        </div>
      </div>
    </div>

    <div class="col-lg-3 col-md-6">
      <div class="card card-transparent b-1 h-200px">
        <header class="card-header">
          <h4 class="card-title">EMPTY</h4>
          <a class="btn btn-sm btn-flat btn-info" href="#">Add Widget</a>
        </header>

        <div class="card-body">
          <p>Click the "Add Widget" button to select from the widget options.</p>
        </div>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <h5 class="card-title"><strong>Recent</strong> contacts</h5>

        <div class="media-list media-list-hover media-list-divided scrollable" style="height: 275px">
          <% @active_contacts.order('created_at DESC').each do |contact| %>
            <div class="media media-single">
              <% if contact.created_at > 24.hours.ago %>
                <i class="fa fa-bolt text-yellow"></i>
              <% end %>
              <a href="<%= admin_contact_path(contact.id) %>">
                <span class="avatar avatar-lg status-<%= contact.sales_stage %>"><%= contact.initials %></span>
              </a>

              <div class="media-body">
                <h6><%= contact.print_name %> | <span class="text-<%= contact.sales_stage %>"><%= contact.sales_stage.capitalize %></span></h6>
                <small class="text-fader">From <a href="#" data-toggle="modal" data-target="#contact_form_modal" class="text-blue">Default Contact Form</a></small>
              </div>

              <div class="media-right">
                <a class="btn btn-sm btn-bold btn-round btn-outline btn-secondary w-100px" href="<%= admin_contact_path(contact.id) %>">View</a>
              </div>
            </div>
          <% end %>
        </div>
        <div class="text-center bt-1 border-light p-2">
          <a class="text-uppercase d-block fs-10 fw-500 ls-1" href="/admin/next/contacts">View all contacts</a>
        </div>
      </div>
    </div>



    <div class="col-12">
      <div class="divider text-uppercase fw-500">Analytics</div>
    </div>

  </div>
</div>

<!-- MODAL - Contact form modal -->
<div class="modal fade" id="contact_form_modal" tabindex="-1">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Contact Form</h4>
        <button type="button" class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-sm-6">
            <p>Form: <strong>Default Contact Form</strong></p>
          </div>
          <div class="col-sm-6">
            <p>Submitted: <strong>05/28/18</strong></p>
          </div>
        </div>
        <h5>Form Contents</h5>
        <p>All the of the form fields and answers will be listed here</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-bold btn-pure btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-bold btn-pure btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/next/dashboard/media.html.erb
<h1>Dashboard: Media</h1>

app/views/next/partials/_breadcrumb.html.erb
<div class="header-bar header-inverse bg-info">
  <a href="<%= link %>" style="color: #fff;"><i class="ti-arrow-left"></i> Back to <%= page %></a>
</div>

app/views/next/website/index.html.erb
<!-- Page aside -->
<aside class="aside aside-expand-md">
  <div class="aside-body">

    <div class="aside-block">
      <h6 class="aside-title">Actions</h6>
    </div>

    <div class="media-list media-list-sm media-list-hover media-list-divided">
      <a class="media flex-column px-20" href="#">
        <p>Business Info</p>
        <small>Update general information including logos, address, social media, etc.</small>
      </a>

      <a class="media flex-column px-20" href="#">
        <p>Navigation Menus</p>
        <small>Setup and organize your site menus</small>
      </a>

      <a class="media flex-column px-20" href="#">
        <p>Contact Forms</p>
        <small>Create, update and view current contact forms available.</small>
      </a>

      <a class="media flex-column px-20" href="#">
        <p>Integrations</p>
        <small>Control permissions and access to other applications</small>
      </a>

    </div>

  </div>

  <button class="aside-toggler"></button>
</aside>
<!-- END Page aside -->

<header class="header no-border">
  <div class="header-bar bg-info">
    <h4 class="">Website</h4>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="#">Home</a></li>
      <li class="breadcrumb-item active">Website</li>
    </ol>
  </div>
</header>

<div class="main-content">
  <div class="row">

    <div class="col-md-6 col-xl-3">
      <div class="card">
        <div class="card-body text-center">
          <a href="#">
            <img class="h-150px" src="https://flexxsirv.sirv.com/8e7fa0231c00fb60b86fba63f0519c90838a643975/5086_-_Web_Shop.png">
          </a>
          <h5 class="mb-1"><a class="hover-info" href="#">Landing Pages</a></h5>
        </div>

        <div class="flexbox flex-justified bt-1 border-light py-12 bg-lightest text-center">
          <a class="text-muted pt-2" href="<%= admin_next_website_new_page_url %>">
            <i class="ti-plus fs-25"></i><br>
            Create
          </a>
          <a class="text-muted pt-2" href="#">
            <i class="ti-view-grid fs-25"></i><br>
            View
          </a>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-xl-3">
      <div class="card">
        <div class="card-body text-center">
          <a href="#">
            <img class="h-150px" src="https://flexxsirv.sirv.com/8e7fa0231c00fb60b86fba63f0519c90838a643975/5086_-_Web_Shop.png">
          </a>
          <h5 class="mb-1"><a class="hover-info" href="#">General Pages</a></h5>
        </div>

        <div class="flexbox flex-justified bt-1 border-light py-12 bg-lightest text-center">
          <a class="text-muted pt-2" href="#">
            <i class="ti-plus fs-25"></i><br>
            Create
          </a>
          <a class="text-muted pt-2" href="#">
            <i class="ti-view-grid fs-25"></i><br>
            View
          </a>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-xl-3">
      <div class="card">
        <div class="card-body text-center">
          <a href="#">
            <img class="h-150px" src="https://flexxsirv.sirv.com/8e7fa0231c00fb60b86fba63f0519c90838a643975/5086_-_Web_Shop.png">
          </a>
          <h5 class="mb-1"><a class="hover-info" href="#">Services</a></h5>
        </div>

        <div class="flexbox flex-justified bt-1 border-light py-12 bg-lightest text-center">
          <a class="text-muted pt-2" href="#">
            <i class="ti-plus fs-25"></i><br>
            Create
          </a>
          <a class="text-muted pt-2" href="#">
            <i class="ti-view-grid fs-25"></i><br>
            View
          </a>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-xl-3">
      <div class="card">
        <div class="card-body text-center">
          <a href="#">
            <img class="h-150px" src="https://flexxsirv.sirv.com/8e7fa0231c00fb60b86fba63f0519c90838a643975/5086_-_Web_Shop.png">
          </a>
          <h5 class="mb-1"><a class="hover-info" href="#">Coaches</a></h5>
        </div>

        <div class="flexbox flex-justified bt-1 border-light py-12 bg-lightest text-center">
          <a class="text-muted pt-2" href="#">
            <i class="ti-plus fs-25"></i><br>
            Create
          </a>
          <a class="text-muted pt-2" href="#">
            <i class="ti-view-grid fs-25"></i><br>
            View
          </a>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-xl-3">
      <div class="card">
        <div class="card-body text-center">
          <a href="#">
            <img class="h-150px" src="https://flexxsirv.sirv.com/8e7fa0231c00fb60b86fba63f0519c90838a643975/5086_-_Web_Shop.png">
          </a>
          <h5 class="mb-1"><a class="hover-info" href="#">Testimonials</a></h5>
        </div>

        <div class="flexbox flex-justified bt-1 border-light py-12 bg-lightest text-center">
          <a class="text-muted pt-2" href="#">
            <i class="ti-plus fs-25"></i><br>
            Create
          </a>
          <a class="text-muted pt-2" href="#">
            <i class="ti-view-grid fs-25"></i><br>
            View
          </a>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/plugins/flexx_plugin_next_admin/front/index.html.erb
<%#= javascript_include_tag plugin_gem_asset("js/my_file.js") %>
Plugin ready to use! in frontend.